---
title: "ANLY 699"
author: "Gaurav Gade"
date: "11/18/2021"
output: pdf_document
---

```{r setup, include=FALSE}
# install.packages("xts")
# install.packages("dplyr")


library(dplyr)
library(xts)
library(cluster)
getwd()
setwd("C:/Users/nagar/Documents/ANLY 699 final project/Defi Datasets")



```

```{r Data preparation, cleaning and normalization}
#========DATA PREP==========================

    
#Import data for DeFi Tokens and BTC - BTC, CARDANO, CHAINLINK, POLKADOT, SOLANA
    
#Import data for each of the four securities - BTC
    data.BTC <- read.csv("C:/Users/nagar/Documents/ANLY 699 final project/Defi Datasets/BTC-USD.csv",header=TRUE)
    date <- as.Date(data.BTC$Date,format="%Y-%m-%d")  
    data.BTC <- cbind(date, data.BTC[,-1])
    data.BTC <- data.BTC[order(data.BTC$date),]
    data.BTC <- xts(data.BTC[,2:7],order.by=data.BTC[,1])
    names(data.BTC) <- paste(c("BTC.Open","BTC.High","BTC.Low","BTC.Close","BTC.Adjusted","BTC.Volume"))
    data.BTC[c(1:3,nrow(data.BTC)),]

#Import data for each of the four securities - Cardano
    data.ADA <- read.csv("C:/Users/nagar/Documents/ANLY 699 final project/Defi Datasets/ADA-USD.csv",header=TRUE)
    date <- as.Date(data.ADA$Date,format="%Y-%m-%d")  
    data.ADA <- cbind(date, data.ADA[,-1])
    data.ADA <- data.ADA[order(data.ADA$date),]
    data.ADA <- xts(data.ADA[,2:7],order.by=data.ADA[,1])
    names(data.ADA) <- paste(c("ADA.Open","ADA.High","ADA.Low","ADA.Close","ADA.Adjusted","ADA.Volume"))
    data.ADA[c(1:3,nrow(data.ADA)),]

#Import data for each of the four securities - ChainLINK (LINK)
    data.LINK <- read.csv("C:/Users/nagar/Documents/ANLY 699 final project/Defi Datasets/LINK-USD.csv",header=TRUE)
    date <- as.Date(data.LINK$Date,format="%Y-%m-%d")  
    data.LINK <- cbind(date, data.LINK[,-1])
    data.LINK <- data.LINK[order(data.LINK$date),]
    data.LINK <- xts(data.LINK[,2:7],order.by=data.LINK[,1])
    names(data.LINK) <- paste(c("LINK.Open","LINK.High","LINK.Low","LINK.Close","LINK.Adjusted","LINK.Volume"))
    data.LINK[c(1:3,nrow(data.LINK)),]

#Import data for each of the four securities - POLKADOT (DOT)
    data.DOT <- read.csv("C:/Users/nagar/Documents/ANLY 699 final project/Defi Datasets/DOT1-USD.csv",header=TRUE)
    date <- as.Date(data.DOT$Date,format="%Y-%m-%d")  
    data.DOT <- cbind(date, data.DOT[,-1])
    data.DOT <- data.DOT[order(data.DOT$date),]
    data.DOT <- xts(data.DOT[,2:7],order.by=data.DOT[,1])
    names(data.DOT) <- paste(c("DOT.Open","DOT.High","DOT.Low","DOT.Close","DOT.Adjusted","DOT.Volume"))
    data.DOT[c(1:3,nrow(data.DOT)),]
    
#Import data for each of the four securities - SOLANA (SOL)
    data.SOL <- read.csv("C:/Users/nagar/Documents/ANLY 699 final project/Defi Datasets/SOL1-USD.csv",header=TRUE)
    date <- as.Date(data.SOL$Date,format="%Y-%m-%d")  
    data.SOL <- cbind(date, data.SOL[,-1])
    data.SOL <- data.SOL[order(data.SOL$date),]
    data.SOL <- xts(data.SOL[,2:7],order.by=data.SOL[,1])
    names(data.SOL) <- paste(c("SOL.Open","SOL.High","SOL.Low","SOL.Close","SOL.Adjusted","SOL.Volume"))
    data.SOL[c(1:3,nrow(data.SOL)),]
    
    
    data.ADA <- subset(data.ADA,
                        index(data.ADA)>"2021-03-31")

    data.BTC <- subset(data.BTC,
                        index(data.BTC)>"2021-03-31")

    data.DOT <- subset(data.DOT,
                        index(data.DOT)>"2021-03-31")

    data.LINK <- subset(data.LINK,
                        index(data.LINK)>"2021-03-31")

    data.SOL <- subset(data.SOL,
                        index(data.SOL)>"2021-03-31")


    #summary(data.ADA)
```   

```{r Combine Data}    
    #Combine Data Into one Data Object
    Close.Prices <- cbind(data.BTC$BTC.Close, data.ADA$ADA.Close,data.LINK$LINK.Close,data.SOL$SOL.Close, data.DOT$DOT.Close)
    Close.Prices[c(1:3,nrow(Close.Prices)),]


    
#Convert Data into a data.frame
    
    multi.df <- cbind(index(Close.Prices),data.frame(Close.Prices))
    names(multi.df) <- paste(c("date","BTC","ADA","LINK","DOT","SOL"))
    rownames(multi.df) <- seq(1,nrow(multi.df),1)
    multi.df[c(1:3,nrow(multi.df)),]

    
    multi.df$ADA <- as.numeric(multi.df$ADA)
    multi.df$BTC <- as.numeric(multi.df$BTC)
    multi.df$LINK <- as.numeric(multi.df$LINK)
    multi.df$DOT <- as.numeric(multi.df$DOT)
    multi.df$SOL <- as.numeric(multi.df$SOL)
  
    
    multi.df <- na.omit(multi.df)
    
    
    #Calculate Normalized Values for Each Security
#Create an index for each security with values that equal the price of the 	security on each day divided by the security's price on December 31, 	2010.

  
    
    
    multi.df$BTC.idx <- multi.df$BTC/multi.df$BTC[1]
    multi.df$ADA.idx <- multi.df$ADA/multi.df$ADA[1]
    multi.df$LINK.idx <- multi.df$LINK/multi.df$LINK[1]
    multi.df$SOL.idx <- multi.df$SOL/multi.df$SOL[1]
    multi.df$DOT.idx <- multi.df$DOT/multi.df$DOT[1]
    
    options(digits=5)   # this option remains in place until end of session
    multi.df[c(1:3,nrow(multi.df)),]    



```

```{r training & test}

    ADA <- as.data.frame(data.ADA)
    BTC <- as.data.frame(data.BTC)
    LINK <- as.data.frame(data.LINK)    
    DOT <- as.data.frame(data.DOT)    
    SOL <- as.data.frame(data.SOL)
    
    defi <- cbind.data.frame(ADA,BTC, LINK,DOT, SOL)
    summary(defi)
    
    
    defi.train <- defi 
    #Dropping volume variable
    defi.train <- defi.train[-c(6,12,18,24,30)]
    

    defi.train$ADA.Open <- as.numeric(unlist(defi.train$ADA.Open))
    defi.train$ADA.High <- as.numeric(unlist(defi.train$ADA.High))
    defi.train$ADA.Low <- as.numeric(unlist(defi.train$ADA.Low))
    defi.train$ADA.Close <- as.numeric(unlist(defi.train$ADA.Close))
    defi.train$ADA.Adjusted <- as.numeric(unlist(defi.train$ADA.Adjusted))
    
    defi.train$BTC.Open <- as.numeric(unlist(defi.train$BTC.Open))
    defi.train$BTC.High <- as.numeric(unlist(defi.train$BTC.High))
    defi.train$BTC.Low <- as.numeric(unlist(defi.train$BTC.Low))
    defi.train$BTC.Close <- as.numeric(unlist(defi.train$BTC.Close))
    defi.train$BTC.Adjusted <- as.numeric(unlist(defi.train$BTC.Adjusted))
    
    defi.train$LINK.Open <- as.numeric(unlist(defi.train$LINK.Open))
    defi.train$LINK.High <- as.numeric(unlist(defi.train$LINK.High))
    defi.train$LINK.Low <- as.numeric(unlist(defi.train$LINK.Low))
    defi.train$LINK.Close <- as.numeric(unlist(defi.train$LINK.Close))
    defi.train$LINK.Adjusted <- as.numeric(unlist(defi.train$LINK.Adjusted))
    
    defi.train$DOT.Open <- as.numeric(unlist(defi.train$DOT.Open))
    defi.train$DOT.High <- as.numeric(unlist(defi.train$DOT.High))
    defi.train$DOT.Low <- as.numeric(unlist(defi.train$DOT.Low))
    defi.train$DOT.Close <- as.numeric(unlist(defi.train$DOT.Close))
    defi.train$DOT.Adjusted <- as.numeric(unlist(defi.train$DOT.Adjusted))
    
     defi.train$SOL.Open <- as.numeric(unlist(defi.train$SOL.Open))
    defi.train$SOL.High <- as.numeric(unlist(defi.train$SOL.High))
    defi.train$SOL.Low <- as.numeric(unlist(defi.train$SOL.Low))
    defi.train$SOL.Close <- as.numeric(unlist(defi.train$SOL.Close))
    defi.train$SOL.Adjusted <- as.numeric(unlist(defi.train$SOL.Adjusted))
    
    
    head(defi.train)
    
    
    defi.training <- defi.train[1:165,]
    defi.test <- defi.training[166:207,]


```


```{r LSTM}
# 
# install.packages("keras")
library(keras)
install_keras()

# library(keras)
# library(tensorflow)
# install_tensorflow()
# use_condaenv("r-tensorflow")

# install_keras()
# install_tensorflow(version = "nightly")

prediction <- 12
lag <- prediction

scaled_train <- as.matrix(ADA$ADA.Close)
 


# we lag the data 11 times and arrange that into columns
x_train_data<- t(sapply(
    1:(length(scaled_train) - lag - prediction + 1),
    function(x) scaled_train[x:(x + lag - 1), 1]
  ))
 
# now we transform it into 3D form
x_train_arr <- array(
    data = as.numeric(unlist(x_train_data)),
    dim = c(
        nrow(x_train_data),
        lag,
        1
    )
)


head(x_train_arr)

y_train_data <- t(sapply(
    (1 + lag):(length(scaled_train) - prediction + 1),
    function(x) scaled_train[x:(x + prediction - 1)]
))

y_train_arr <- array(
    data = as.numeric(unlist(y_train_data)),
    dim = c(
        nrow(y_train_data),
        prediction,
        1
    )
)

y_train_data <- t(sapply(
    (1 + lag):(length(scaled_train) - prediction + 1),
    function(x) scaled_train[x:(x + prediction - 1)]
))

y_train_arr <- array(
    data = as.numeric(unlist(y_train_data)),
    dim = c(
        nrow(y_train_data),
        prediction,
        1
    )
)

y_train_arr <- na.omit(y_train_arr)

x_test <- ADA$ADA.Close[(nrow(scaled_train) - prediction + 1):nrow(scaled_train)]

x_test <- na.omit(x_test)

x_test <- as.numeric(x_test)
# scale the data with same scaling factors as for training

scale_factors <- c(mean(as.numeric(ADA$ADA.Close)), sd(as.numeric(ADA$ADA.Close)))

x_test_scaled <- (x_test - scale_factors[1]) / scale_factors[2]

# this time our array just has one sample, as we intend to perform one 12-months prediction
x_pred_arr <- array(
    data = x_test_scaled,
    dim = c(
        1,
        lag,
        1
    )
)
x_test <- na.omit
x_test_scaled
x_pred_arr

lstm_model <- keras_model_sequential()

lstm_model %>%
  layer_lstm(units = 50, # size of the layer
       batch_input_shape = c(1, 12, 1), # batch size, timesteps, features
       return_sequences = TRUE,
       stateful = TRUE) %>%
  # fraction of the units to drop for the linear transformation of the inputs
  layer_dropout(rate = 0.5) %>%
  layer_lstm(units = 50,
        return_sequences = TRUE,
        stateful = TRUE) %>%
  layer_dropout(rate = 0.5) %>%
  time_distributed(keras::layer_dense(units = 1))

lstm_model %>%
    compile(loss = 'mae', optimizer = 'adam', metrics = 'accuracy')

summary(lstm_model)

lstm_model %>% fit(
    x = x_train_arr,
    y = y_train_arr,
    batch_size = 1,
    epochs = 20,
    verbose = 0,
    shuffle = FALSE
)

lstm_forecast <- lstm_model %>%
    predict(x_pred_arr, batch_size = 1) %>%
    .[, , 1]

# we need to rescale the data to restore the original values
lstm_forecast <- lstm_forecast * scale_factors[2] + scale_factors[1]

lstm_forecast

lstm_forecast <- lstm_model %>%
    predict(x_pred_arr, batch_size = 1) %>%
    .[, , 1]

# we need to rescale the data to restore the original values
lstm_forecast <- lstm_forecast * scale_factors[2] + scale_factors[1]
 fitted <- predict(lstm_model, x_train_arr, batch_size = 1) %>%
     .[, , 1]

if (dim(fitted)[2] > 1) {
    fit <- c(fitted[, 1], fitted[dim(fitted)[1], 2:dim(fitted)[2]])
} else {
    fit <- fitted[, 1]
}

# additionally we need to rescale the data
fitted <- fit * scale_factors[2] + scale_factors[1]

fitted <- c(rep(NA, lag), fitted)

library(timetk)

lstm_forecast <- timetk::tk_ts(lstm_forecast,
    start = c(2020, 10),
    end = c(2021, 10),
    frequency = 12
)


lstm_forecast

input_ts <- timetk::tk_ts(ADA$ADA.Close, 
    start = c(2020, 10), 
    end = c(2021, 10), 
    frequency = 12)

forecast_list <- list(
    model = NULL,
    method = "LSTM",
    mean = lstm_forecast,
    x = input_ts,
    fitted = fitted,
    residuals = as.numeric(input_ts) - as.numeric(fitted)
  )

class(forecast_list) <- "forecast"

forecast::autoplot(forecast_list)



```


